import { FlatfileClient } from "@flatfile/api";
import { FlatfileListener } from "@flatfile/listener";
import { recordHook } from "@flatfile/plugin-record-hook";
import { format, isDate, isFuture, parseISO } from "date-fns";

const flatfile = new FlatfileClient({
  token: process.env.FLATFILE_API_KEY,
  environment: process.env.BASE_URL + "/v1",
});

export const listener = FlatfileListener.create((listener) => {
  listener.on("**", (event) => {
    console.log("Event =>", event.topic);
  });

  // listener.use(
  //   recordHook("contacts", (record) => {

  //     if (record.get('email')) {
  //       const email = record.get("email")
  //       const validEmailAddress = /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/;
  //       if (!validEmailAddress.test(email)) {
  //         console.log("Invalid email address");
  //         record.addError("email", "Must be a valid email address");
  //       }
  //     }

  //     if (record.get('country')) {
  //       const country = record.get("country")
  //       const validCountry = /^[A-Z]{2}$/;
  //       if (!validCountry.test(country)) {
  //         // console.log("Invalid country");
  //         record.addError("country", "Must be two char country code");
  //       }
  //     }

  //     if (record.get('firstName') && !record.get('lastName')) {
  //       const fName = record.get('firstName')
  //       if (fName.includes(" ")) {
  //         const components = fName.split(" ");
  //         record.set('firstName', components.shift());
  //         record.set('lastName', components.join(" "));
  //         record.addInfo('lastName', 'Automatically generated from full name')
  //       }
  //     }

  //     if (record.get('firstName') && record.get('lastName') && !record.get('fullName')) {
  //       const fullName = `${record.get('firstName')} ${record.get('lastName')}`
  //       record.set('fullName', fullName)
  //       record.addInfo('fullName', 'System generated by combining first and last name.')
  //     }

  //     if (!record.get('phone') && !record.get('email')) {
  //       record.addWarning('phone', 'Please inlclude one of either phone or email')
  //       record.addWarning('email', 'Please inlclude one of either phone or email')
  //     }

  //     if (record.get('date')) {
  //       //reformat the date to ISO format
  //       const date = record.get('date')
  //       let thisDate = format(new Date(date), "yyyy-MM-dd");
  //       //create var that holds the date value of the reformatted date as
  //       //thisDate is only a string
  //       let realDate = parseISO(thisDate);
  //       if (isDate(realDate)) {
  //         record.set('date', thisDate)
  //         if (isFuture(realDate)) {
  //           record.addError('date', 'Date cannot be in the future.')
  //         }
  //       } else {
  //         record.addError('date', 'Please check that the date is formatted YYYY-MM-DD.')
  //       }
  //     }

  //     if (record.get('zipCode') && record.get('country')) {
  //       const zip = record.get('zipCode')
  //       const country = record.get('country')
  //       if (zip && zip.length < 5 && country === "US") {
  //         record.set('zipCode', zip.padStart(5, '0'))
  //         record.addInfo('zipCode', 'Zipcode was padded with zeroes')
  //       }
  //     }

  //     // if (record.get('ccName')) {
  //     //   const links = record.getLinks('ccName')
  //     //   const lookupValue = links?.[0]?.['code']
  //     //   const targetField = 'ccId'
  //     //   record.set(targetField, lookupValue)
  //     //   record.addInfo(targetField, 'From linked file')
  //     // }

  //     if (record.get('ccId')) {
  //       const links = record.getLinks('ccId')
  //       const lookupValue = links?.[0]?.['name']
  //       const targetField = 'ccName'
  //       record.set(targetField, lookupValue)
  //       record.addInfo(targetField, 'From linked file')
  //     }

  //     // if (record.get('numberTest')) {
  //     //   const numbersOnly = record.get('numberTest') as string
  //     //   console.log(`NumbersOnly, ${numbersOnly}`)
  //     //   const validNumberRegex = /\D/;
  //     //   if (validNumberRegex.test(numbersOnly)) {
  //     //     console.log('bad number')
  //     //     record.addError('numberTest', 'Must be a number')
  //     //   }
  //     // }

  //     return record;

  //   })
  // );

  // listener.on(
  //   "job:ready",
  //   { job: "workbook:submitActionFg" },
  //   async ({ context: { jobId } }) => {
  //     try {
  //       await flatfile.jobs.ack(jobId, {
  //         info: "Getting started.",
  //         progress: 10,
  //       });

  //       // Make changes after cells in a Sheet have been updated
  //       console.log("Make changes here when an action is clicked");

  //       await flatfile.jobs.complete(jobId, {
  //         outcome: {
  //           message: "This job is now complete.",
  //         },
  //       });
  //     } catch (error) {
  //       console.error("Error:", error.stack);

  //       await flatfile.jobs.fail(jobId, {
  //         outcome: {
  //           message: "This job encountered an error.",
  //         },
  //       });
  //     }
  //   }
  // );
});
